CREATE DATABASE CLINICA_PET_TARDE;

CREATE TABLE DONOS(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(100) NOT NULL
);

CREATE TABLE TIPO_DE_PETS(
	ID INT IDENTITY PRIMARY KEY
	,DESCRICAO VARCHAR(100) NOT NULL
);

CREATE TABLE RACAS(
	ID INT IDENTITY PRIMARY KEY
	,DESCRICAO VARCHAR(100)
	,ID_TIPO_PET INT FOREIGN KEY REFERENCES TIPO_DE_PETS (ID)
);

CREATE TABLE CLINICAS(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(100) NOT NULL
	,ENDERECO VARCHAR(255) NOT NULL
);

CREATE TABLE VETERINARIOS(
	ID INT IDENTITY PRIMARY KEY
	,CRMV CHAR(6) NOT NULL UNIQUE
	,NOME VARCHAR(100) NOT NULL
	,ID_CLINICA INT FOREIGN KEY REFERENCES CLINICAS (ID)
);

CREATE TABLE PETS(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(100) NOT NULL
	,DATA_NASCIMENTO DATE NOT NULL
	,ID_RACA_PET INT FOREIGN KEY REFERENCES RACAS (ID)
	,ID_DONO INT FOREIGN KEY REFERENCES DONOS (ID)
);

CREATE TABLE ATENDIMENTOS(
	ID INT IDENTITY PRIMARY KEY
	,ID_PET INT FOREIGN KEY REFERENCES PETS (ID)
	,ID_VET INT FOREIGN KEY REFERENCES VETERINARIOS (ID)
	,DESCRICAO VARCHAR(255)
	,DT_ATENDIMENTO DATETIME NOT NULL
);